#!/bin/bash
# Dependencies: scrot, xsel

# Configuration
BROWSER=/usr/bin/firefox
SCP_USER=username
SCP_HOST=yourwebhost.com
SCP_PATH=public_html/grabup
URL_BASE=http://www.yourwebhost.com/grabup

NOW=`date +%Y-%m-%d_%H.%M.%S`
TEMPDIR=/tmp/grabup
FILENAME=$NOW.png
mkdir -p $TEMPDIR
sleep 0.5 # Wait for key release so scrot can capture
scrot -s $TEMPDIR/$FILENAME
scp $TEMPDIR/$FILENAME $SCP_USER@$SCP_HOST:$SCP_PATH/
URL=$URL_BASE/$FILENAME
echo $URL | xsel -i --clipboard
echo $URL | xsel -i --primary
$BROWSER $URL &
